use device_query::Keycode;
use enigo::Key;
use strum_macros::EnumIter;

// Re-export the `Keycode` enum from the `device_query` crate.
#[derive(
    Debug, Eq, PartialEq, Hash, Clone, Copy, serde::Deserialize, serde::Serialize, EnumIter,
)]
#[allow(missing_docs)]
pub enum AppKeycode {
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Escape,
    Space,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    Command,
    LOption,
    ROption,
    LMeta,
    RMeta,
    Enter,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    CapsLock,
    Tab,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadSubtract,
    NumpadAdd,
    NumpadDivide,
    NumpadMultiply,
    NumpadEquals,
    NumpadEnter,
    NumpadDecimal,
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
}

impl AppKeycode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Key0 => "0",
            Self::Key1 => "1",
            Self::Key2 => "2",
            Self::Key3 => "3",
            Self::Key4 => "4",
            Self::Key5 => "5",
            Self::Key6 => "6",
            Self::Key7 => "7",
            Self::Key8 => "8",
            Self::Key9 => "9",
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::W => "W",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::F13 => "F13",
            Self::F14 => "F14",
            Self::F15 => "F15",
            Self::F16 => "F16",
            Self::F17 => "F17",
            Self::F18 => "F18",
            Self::F19 => "F19",
            Self::F20 => "F20",
            Self::Escape => "Escape",
            Self::Space => "Space",
            Self::LControl => "LControl",
            Self::RControl => "RControl",
            Self::LShift => "LShift",
            Self::RShift => "RShift",
            Self::LAlt => "LAlt",
            Self::RAlt => "RAlt",
            Self::Command => "Command",
            Self::LOption => "LOption",
            Self::ROption => "ROption",
            Self::LMeta => "LMeta",
            Self::RMeta => "RMeta",
            Self::Enter => "Enter",
            Self::Up => "Up",
            Self::Down => "Down",
            Self::Left => "Left",
            Self::Right => "Right",
            Self::Backspace => "Backspace",
            Self::CapsLock => "CapsLock",
            Self::Tab => "Tab",
            Self::Home => "Home",
            Self::End => "End",
            Self::PageUp => "PageUp",
            Self::PageDown => "PageDown",
            Self::Insert => "Insert",
            Self::Delete => "Delete",
            Self::Numpad0 => "Numpad0",
            Self::Numpad1 => "Numpad1",
            Self::Numpad2 => "Numpad2",
            Self::Numpad3 => "Numpad3",
            Self::Numpad4 => "Numpad4",
            Self::Numpad5 => "Numpad5",
            Self::Numpad6 => "Numpad6",
            Self::Numpad7 => "Numpad7",
            Self::Numpad8 => "Numpad8",
            Self::Numpad9 => "Numpad9",
            Self::NumpadSubtract => "NumpadSubtract",
            Self::NumpadAdd => "NumpadAdd",
            Self::NumpadDivide => "NumpadDivide",
            Self::NumpadMultiply => "NumpadMultiply",
            Self::NumpadEquals => "NumpadEquals",
            Self::NumpadEnter => "NumpadEnter",
            Self::NumpadDecimal => "NumpadDecimal",
            Self::Grave => "Grave",
            Self::Minus => "Minus",
            Self::Equal => "Equal",
            Self::LeftBracket => "LeftBracket",
            Self::RightBracket => "RightBracket",
            Self::BackSlash => "BackSlash",
            Self::Semicolon => "Semicolon",
            Self::Apostrophe => "Apostrophe",
            Self::Comma => "Comma",
            Self::Dot => "Dot",
            Self::Slash => "Slash",
        }
    }
}

impl From<device_query::Keycode> for AppKeycode {
    fn from(value: Keycode) -> Self {
        match value {
            Keycode::Key0 => AppKeycode::Key0,
            Keycode::Key1 => AppKeycode::Key1,
            Keycode::Key2 => AppKeycode::Key2,
            Keycode::Key3 => AppKeycode::Key3,
            Keycode::Key4 => AppKeycode::Key4,
            Keycode::Key5 => AppKeycode::Key5,
            Keycode::Key6 => AppKeycode::Key6,
            Keycode::Key7 => AppKeycode::Key7,
            Keycode::Key8 => AppKeycode::Key8,
            Keycode::Key9 => AppKeycode::Key9,
            Keycode::A => AppKeycode::A,
            Keycode::B => AppKeycode::B,
            Keycode::C => AppKeycode::C,
            Keycode::D => AppKeycode::D,
            Keycode::E => AppKeycode::E,
            Keycode::F => AppKeycode::F,
            Keycode::G => AppKeycode::G,
            Keycode::H => AppKeycode::H,
            Keycode::I => AppKeycode::I,
            Keycode::J => AppKeycode::J,
            Keycode::K => AppKeycode::K,
            Keycode::L => AppKeycode::L,
            Keycode::M => AppKeycode::M,
            Keycode::N => AppKeycode::N,
            Keycode::O => AppKeycode::O,
            Keycode::P => AppKeycode::P,
            Keycode::Q => AppKeycode::Q,
            Keycode::R => AppKeycode::R,
            Keycode::S => AppKeycode::S,
            Keycode::T => AppKeycode::T,
            Keycode::U => AppKeycode::U,
            Keycode::V => AppKeycode::V,
            Keycode::W => AppKeycode::W,
            Keycode::X => AppKeycode::X,
            Keycode::Y => AppKeycode::Y,
            Keycode::Z => AppKeycode::Z,
            Keycode::F1 => AppKeycode::F1,
            Keycode::F2 => AppKeycode::F2,
            Keycode::F3 => AppKeycode::F3,
            Keycode::F4 => AppKeycode::F4,
            Keycode::F5 => AppKeycode::F5,
            Keycode::F6 => AppKeycode::F6,
            Keycode::F7 => AppKeycode::F7,
            Keycode::F8 => AppKeycode::F8,
            Keycode::F9 => AppKeycode::F9,
            Keycode::F10 => AppKeycode::F10,
            Keycode::F11 => AppKeycode::F11,
            Keycode::F12 => AppKeycode::F12,
            Keycode::F13 => AppKeycode::F13,
            Keycode::F14 => AppKeycode::F14,
            Keycode::F15 => AppKeycode::F15,
            Keycode::F16 => AppKeycode::F16,
            Keycode::F17 => AppKeycode::F17,
            Keycode::F18 => AppKeycode::F18,
            Keycode::F19 => AppKeycode::F19,
            Keycode::F20 => AppKeycode::F20,
            Keycode::Escape => AppKeycode::Escape,
            Keycode::Space => AppKeycode::Space,
            Keycode::LControl => AppKeycode::LControl,
            Keycode::RControl => AppKeycode::RControl,
            Keycode::LShift => AppKeycode::LShift,
            Keycode::RShift => AppKeycode::RShift,
            Keycode::LAlt => AppKeycode::LAlt,
            Keycode::RAlt => AppKeycode::RAlt,
            Keycode::Command => AppKeycode::Command,
            Keycode::LOption => AppKeycode::LOption,
            Keycode::ROption => AppKeycode::ROption,
            Keycode::LMeta => AppKeycode::LMeta,
            Keycode::RMeta => AppKeycode::RMeta,
            Keycode::Enter => AppKeycode::Enter,
            Keycode::Up => AppKeycode::Up,
            Keycode::Down => AppKeycode::Down,
            Keycode::Left => AppKeycode::Left,
            Keycode::Right => AppKeycode::Right,
            Keycode::Backspace => AppKeycode::Backspace,
            Keycode::CapsLock => AppKeycode::CapsLock,
            Keycode::Tab => AppKeycode::Tab,
            Keycode::Home => AppKeycode::Home,
            Keycode::End => AppKeycode::End,
            Keycode::PageUp => AppKeycode::PageUp,
            Keycode::PageDown => AppKeycode::PageDown,
            Keycode::Insert => AppKeycode::Insert,
            Keycode::Delete => AppKeycode::Delete,
            Keycode::Numpad0 => AppKeycode::Numpad0,
            Keycode::Numpad1 => AppKeycode::Numpad1,
            Keycode::Numpad2 => AppKeycode::Numpad2,
            Keycode::Numpad3 => AppKeycode::Numpad3,
            Keycode::Numpad4 => AppKeycode::Numpad4,
            Keycode::Numpad5 => AppKeycode::Numpad5,
            Keycode::Numpad6 => AppKeycode::Numpad6,
            Keycode::Numpad7 => AppKeycode::Numpad7,
            Keycode::Numpad8 => AppKeycode::Numpad8,
            Keycode::Numpad9 => AppKeycode::Numpad9,
            Keycode::NumpadSubtract => AppKeycode::NumpadSubtract,
            Keycode::NumpadAdd => AppKeycode::NumpadAdd,
            Keycode::NumpadDivide => AppKeycode::NumpadDivide,
            Keycode::NumpadMultiply => AppKeycode::NumpadMultiply,
            Keycode::NumpadEquals => AppKeycode::NumpadEquals,
            Keycode::NumpadEnter => AppKeycode::NumpadEnter,
            Keycode::NumpadDecimal => AppKeycode::NumpadDecimal,
            Keycode::Grave => AppKeycode::Grave,
            Keycode::Minus => AppKeycode::Minus,
            Keycode::Equal => AppKeycode::Equal,
            Keycode::LeftBracket => AppKeycode::LeftBracket,
            Keycode::RightBracket => AppKeycode::RightBracket,
            Keycode::BackSlash => AppKeycode::BackSlash,
            Keycode::Semicolon => AppKeycode::Semicolon,
            Keycode::Apostrophe => AppKeycode::Apostrophe,
            Keycode::Comma => AppKeycode::Comma,
            Keycode::Dot => AppKeycode::Dot,
            Keycode::Slash => AppKeycode::Slash,
        }
    }
}

impl From<AppKeycode> for device_query::Keycode {
    fn from(val: AppKeycode) -> Self {
        match val {
            AppKeycode::Key0 => Keycode::Key0,
            AppKeycode::Key1 => Keycode::Key1,
            AppKeycode::Key2 => Keycode::Key2,
            AppKeycode::Key3 => Keycode::Key3,
            AppKeycode::Key4 => Keycode::Key4,
            AppKeycode::Key5 => Keycode::Key5,
            AppKeycode::Key6 => Keycode::Key6,
            AppKeycode::Key7 => Keycode::Key7,
            AppKeycode::Key8 => Keycode::Key8,
            AppKeycode::Key9 => Keycode::Key9,
            AppKeycode::A => Keycode::A,
            AppKeycode::B => Keycode::B,
            AppKeycode::C => Keycode::C,
            AppKeycode::D => Keycode::D,
            AppKeycode::E => Keycode::E,
            AppKeycode::F => Keycode::F,
            AppKeycode::G => Keycode::G,
            AppKeycode::H => Keycode::H,
            AppKeycode::I => Keycode::I,
            AppKeycode::J => Keycode::J,
            AppKeycode::K => Keycode::K,
            AppKeycode::L => Keycode::L,
            AppKeycode::M => Keycode::M,
            AppKeycode::N => Keycode::N,
            AppKeycode::O => Keycode::O,
            AppKeycode::P => Keycode::P,
            AppKeycode::Q => Keycode::Q,
            AppKeycode::R => Keycode::R,
            AppKeycode::S => Keycode::S,
            AppKeycode::T => Keycode::T,
            AppKeycode::U => Keycode::U,
            AppKeycode::V => Keycode::V,
            AppKeycode::W => Keycode::W,
            AppKeycode::X => Keycode::X,
            AppKeycode::Y => Keycode::Y,
            AppKeycode::Z => Keycode::Z,
            AppKeycode::F1 => Keycode::F1,
            AppKeycode::F2 => Keycode::F2,
            AppKeycode::F3 => Keycode::F3,
            AppKeycode::F4 => Keycode::F4,
            AppKeycode::F5 => Keycode::F5,
            AppKeycode::F6 => Keycode::F6,
            AppKeycode::F7 => Keycode::F7,
            AppKeycode::F8 => Keycode::F8,
            AppKeycode::F9 => Keycode::F9,
            AppKeycode::F10 => Keycode::F10,
            AppKeycode::F11 => Keycode::F11,
            AppKeycode::F12 => Keycode::F12,
            AppKeycode::F13 => Keycode::F13,
            AppKeycode::F14 => Keycode::F14,
            AppKeycode::F15 => Keycode::F15,
            AppKeycode::F16 => Keycode::F16,
            AppKeycode::F17 => Keycode::F17,
            AppKeycode::F18 => Keycode::F18,
            AppKeycode::F19 => Keycode::F19,
            AppKeycode::F20 => Keycode::F20,
            AppKeycode::Escape => Keycode::Escape,
            AppKeycode::Space => Keycode::Space,
            AppKeycode::LControl => Keycode::LControl,
            AppKeycode::RControl => Keycode::RControl,
            AppKeycode::LShift => Keycode::LShift,
            AppKeycode::RShift => Keycode::RShift,
            AppKeycode::LAlt => Keycode::LAlt,
            AppKeycode::RAlt => Keycode::RAlt,
            AppKeycode::Command => Keycode::Command,
            AppKeycode::LOption => Keycode::LOption,
            AppKeycode::ROption => Keycode::ROption,
            AppKeycode::LMeta => Keycode::LMeta,
            AppKeycode::RMeta => Keycode::RMeta,
            AppKeycode::Enter => Keycode::Enter,
            AppKeycode::Up => Keycode::Up,
            AppKeycode::Down => Keycode::Down,
            AppKeycode::Left => Keycode::Left,
            AppKeycode::Right => Keycode::Right,
            AppKeycode::Backspace => Keycode::Backspace,
            AppKeycode::CapsLock => Keycode::CapsLock,
            AppKeycode::Tab => Keycode::Tab,
            AppKeycode::Home => Keycode::Home,
            AppKeycode::End => Keycode::End,
            AppKeycode::PageUp => Keycode::PageUp,
            AppKeycode::PageDown => Keycode::PageDown,
            AppKeycode::Insert => Keycode::Insert,
            AppKeycode::Delete => Keycode::Delete,
            AppKeycode::Numpad0 => Keycode::Numpad0,
            AppKeycode::Numpad1 => Keycode::Numpad1,
            AppKeycode::Numpad2 => Keycode::Numpad2,
            AppKeycode::Numpad3 => Keycode::Numpad3,
            AppKeycode::Numpad4 => Keycode::Numpad4,
            AppKeycode::Numpad5 => Keycode::Numpad5,
            AppKeycode::Numpad6 => Keycode::Numpad6,
            AppKeycode::Numpad7 => Keycode::Numpad7,
            AppKeycode::Numpad8 => Keycode::Numpad8,
            AppKeycode::Numpad9 => Keycode::Numpad9,
            AppKeycode::NumpadSubtract => Keycode::NumpadSubtract,
            AppKeycode::NumpadAdd => Keycode::NumpadAdd,
            AppKeycode::NumpadDivide => Keycode::NumpadDivide,
            AppKeycode::NumpadMultiply => Keycode::NumpadMultiply,
            AppKeycode::NumpadEquals => Keycode::NumpadEquals,
            AppKeycode::NumpadEnter => Keycode::NumpadEnter,
            AppKeycode::NumpadDecimal => Keycode::NumpadDecimal,
            AppKeycode::Grave => Keycode::Grave,
            AppKeycode::Minus => Keycode::Minus,
            AppKeycode::Equal => Keycode::Equal,
            AppKeycode::LeftBracket => Keycode::LeftBracket,
            AppKeycode::RightBracket => Keycode::RightBracket,
            AppKeycode::BackSlash => Keycode::BackSlash,
            AppKeycode::Semicolon => Keycode::Semicolon,
            AppKeycode::Apostrophe => Keycode::Apostrophe,
            AppKeycode::Comma => Keycode::Comma,
            AppKeycode::Dot => Keycode::Dot,
            AppKeycode::Slash => Keycode::Slash,
        }
    }
}

// TODO: Verify this works on all platforms
impl From<AppKeycode> for enigo::Key {
    fn from(value: AppKeycode) -> Self {
        match value {
            AppKeycode::Key0 => Key::Unicode('0'),
            AppKeycode::Key1 => Key::Unicode('1'),
            AppKeycode::Key2 => Key::Unicode('2'),
            AppKeycode::Key3 => Key::Unicode('3'),
            AppKeycode::Key4 => Key::Unicode('4'),
            AppKeycode::Key5 => Key::Unicode('5'),
            AppKeycode::Key6 => Key::Unicode('6'),
            AppKeycode::Key7 => Key::Unicode('7'),
            AppKeycode::Key8 => Key::Unicode('8'),
            AppKeycode::Key9 => Key::Unicode('9'),
            AppKeycode::A => Key::Unicode('a'),
            AppKeycode::B => Key::Unicode('b'),
            AppKeycode::C => Key::Unicode('c'),
            AppKeycode::D => Key::Unicode('d'),
            AppKeycode::E => Key::Unicode('e'),
            AppKeycode::F => Key::Unicode('f'),
            AppKeycode::G => Key::Unicode('g'),
            AppKeycode::H => Key::Unicode('h'),
            AppKeycode::I => Key::Unicode('i'),
            AppKeycode::J => Key::Unicode('j'),
            AppKeycode::K => Key::Unicode('k'),
            AppKeycode::L => Key::Unicode('l'),
            AppKeycode::M => Key::Unicode('m'),
            AppKeycode::N => Key::Unicode('n'),
            AppKeycode::O => Key::Unicode('o'),
            AppKeycode::P => Key::Unicode('p'),
            AppKeycode::Q => Key::Unicode('q'),
            AppKeycode::R => Key::Unicode('r'),
            AppKeycode::S => Key::Unicode('s'),
            AppKeycode::T => Key::Unicode('t'),
            AppKeycode::U => Key::Unicode('u'),
            AppKeycode::V => Key::Unicode('v'),
            AppKeycode::W => Key::Unicode('w'),
            AppKeycode::X => Key::Unicode('x'),
            AppKeycode::Y => Key::Unicode('y'),
            AppKeycode::Z => Key::Unicode('z'),
            AppKeycode::F1 => Key::F1,
            AppKeycode::F2 => Key::F2,
            AppKeycode::F3 => Key::F3,
            AppKeycode::F4 => Key::F4,
            AppKeycode::F5 => Key::F5,
            AppKeycode::F6 => Key::F6,
            AppKeycode::F7 => Key::F7,
            AppKeycode::F8 => Key::F8,
            AppKeycode::F9 => Key::F9,
            AppKeycode::F10 => Key::F10,
            AppKeycode::F11 => Key::F11,
            AppKeycode::F12 => Key::F12,
            AppKeycode::F13 => Key::F13,
            AppKeycode::F14 => Key::F14,
            AppKeycode::F15 => Key::F15,
            AppKeycode::F16 => Key::F16,
            AppKeycode::F17 => Key::F17,
            AppKeycode::F18 => Key::F18,
            AppKeycode::F19 => Key::F19,
            AppKeycode::F20 => Key::F20,
            AppKeycode::Escape => Key::Escape,
            AppKeycode::Space => Key::Space,
            AppKeycode::LControl => Key::LControl,
            AppKeycode::RControl => Key::RControl,
            AppKeycode::LShift => Key::LShift,
            AppKeycode::RShift => Key::RShift,
            AppKeycode::LAlt | AppKeycode::RAlt => Key::Alt,
            AppKeycode::Command => Key::Meta,
            AppKeycode::LOption | AppKeycode::ROption => Key::Option,
            AppKeycode::LMeta | AppKeycode::RMeta => Key::Meta,
            AppKeycode::Enter => Key::Return,
            AppKeycode::Up => Key::UpArrow,
            AppKeycode::Down => Key::DownArrow,
            AppKeycode::Left => Key::LeftArrow,
            AppKeycode::Right => Key::RightArrow,
            AppKeycode::Backspace => Key::Backspace,
            AppKeycode::CapsLock => Key::CapsLock,
            AppKeycode::Tab => Key::Tab,
            AppKeycode::Home => Key::Home,
            AppKeycode::End => Key::End,
            AppKeycode::PageUp => Key::PageUp,
            AppKeycode::PageDown => Key::PageDown,
            // TODO: Check if this is correct
            AppKeycode::Insert => Key::Other(45),
            AppKeycode::Delete => Key::Delete,
            AppKeycode::Numpad0 => Key::Unicode('0'),
            AppKeycode::Numpad1 => Key::Unicode('1'),
            AppKeycode::Numpad2 => Key::Unicode('2'),
            AppKeycode::Numpad3 => Key::Unicode('3'),
            AppKeycode::Numpad4 => Key::Unicode('4'),
            AppKeycode::Numpad5 => Key::Unicode('5'),
            AppKeycode::Numpad6 => Key::Unicode('6'),
            AppKeycode::Numpad7 => Key::Unicode('7'),
            AppKeycode::Numpad8 => Key::Unicode('8'),
            AppKeycode::Numpad9 => Key::Unicode('9'),
            AppKeycode::NumpadSubtract => Key::Unicode('-'),
            AppKeycode::NumpadAdd => Key::Unicode('+'),
            AppKeycode::NumpadDivide => Key::Unicode('/'),
            AppKeycode::NumpadMultiply => Key::Unicode('*'),
            AppKeycode::NumpadEquals => Key::Unicode('='),
            AppKeycode::NumpadEnter => Key::Return,
            AppKeycode::NumpadDecimal => Key::Unicode('.'),
            AppKeycode::Grave => Key::Unicode('`'),
            AppKeycode::Minus => Key::Unicode('-'),
            AppKeycode::Equal => Key::Unicode('='),
            AppKeycode::LeftBracket => Key::Unicode('['),
            AppKeycode::RightBracket => Key::Unicode(']'),
            AppKeycode::BackSlash => Key::Unicode('\\'),
            AppKeycode::Semicolon => Key::Unicode(';'),
            AppKeycode::Apostrophe => Key::Unicode('\''),
            AppKeycode::Comma => Key::Unicode(','),
            AppKeycode::Dot => Key::Unicode('.'),
            AppKeycode::Slash => Key::Unicode('/'),
        }
    }
}
