use device_query::Keycode;
use strum_macros::EnumIter;

// Re-export the `Keycode` enum from the `device_query` crate.
#[derive(
    Debug, Eq, PartialEq, Hash, Clone, Copy, serde::Deserialize, serde::Serialize, EnumIter,
)]
#[allow(missing_docs)]
pub enum AppKeycode {
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Escape,
    Space,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    Command,
    LOption,
    ROption,
    LMeta,
    RMeta,
    Enter,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    CapsLock,
    Tab,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,

    // Numpad keys which have not been implemented: NumpadSeparator NumLock
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadSubtract,
    NumpadAdd,
    NumpadDivide,
    NumpadMultiply,
    NumpadEquals,
    NumpadEnter,
    NumpadDecimal,

    // The following keys names represent the position of the key in a US keyboard,
    // not the sign value. In a different keyboards and OS, the position can vary.
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
}

impl From<Keycode> for AppKeycode {
    fn from(value: Keycode) -> Self {
        match value {
            Keycode::Key0 => AppKeycode::Key0,
            Keycode::Key1 => AppKeycode::Key1,
            Keycode::Key2 => AppKeycode::Key2,
            Keycode::Key3 => AppKeycode::Key3,
            Keycode::Key4 => AppKeycode::Key4,
            Keycode::Key5 => AppKeycode::Key5,
            Keycode::Key6 => AppKeycode::Key6,
            Keycode::Key7 => AppKeycode::Key7,
            Keycode::Key8 => AppKeycode::Key8,
            Keycode::Key9 => AppKeycode::Key9,
            Keycode::A => AppKeycode::A,
            Keycode::B => AppKeycode::B,
            Keycode::C => AppKeycode::C,
            Keycode::D => AppKeycode::D,
            Keycode::E => AppKeycode::E,
            Keycode::F => AppKeycode::F,
            Keycode::G => AppKeycode::G,
            Keycode::H => AppKeycode::H,
            Keycode::I => AppKeycode::I,
            Keycode::J => AppKeycode::J,
            Keycode::K => AppKeycode::K,
            Keycode::L => AppKeycode::L,
            Keycode::M => AppKeycode::M,
            Keycode::N => AppKeycode::N,
            Keycode::O => AppKeycode::O,
            Keycode::P => AppKeycode::P,
            Keycode::Q => AppKeycode::Q,
            Keycode::R => AppKeycode::R,
            Keycode::S => AppKeycode::S,
            Keycode::T => AppKeycode::T,
            Keycode::U => AppKeycode::U,
            Keycode::V => AppKeycode::V,
            Keycode::W => AppKeycode::W,
            Keycode::X => AppKeycode::X,
            Keycode::Y => AppKeycode::Y,
            Keycode::Z => AppKeycode::Z,
            Keycode::F1 => AppKeycode::F1,
            Keycode::F2 => AppKeycode::F2,
            Keycode::F3 => AppKeycode::F3,
            Keycode::F4 => AppKeycode::F4,
            Keycode::F5 => AppKeycode::F5,
            Keycode::F6 => AppKeycode::F6,
            Keycode::F7 => AppKeycode::F7,
            Keycode::F8 => AppKeycode::F8,
            Keycode::F9 => AppKeycode::F9,
            Keycode::F10 => AppKeycode::F10,
            Keycode::F11 => AppKeycode::F11,
            Keycode::F12 => AppKeycode::F12,
            Keycode::F13 => AppKeycode::F13,
            Keycode::F14 => AppKeycode::F14,
            Keycode::F15 => AppKeycode::F15,
            Keycode::F16 => AppKeycode::F16,
            Keycode::F17 => AppKeycode::F17,
            Keycode::F18 => AppKeycode::F18,
            Keycode::F19 => AppKeycode::F19,
            Keycode::F20 => AppKeycode::F20,
            Keycode::Escape => AppKeycode::Escape,
            Keycode::Space => AppKeycode::Space,
            Keycode::LControl => AppKeycode::LControl,
            Keycode::RControl => AppKeycode::RControl,
            Keycode::LShift => AppKeycode::LShift,
            Keycode::RShift => AppKeycode::RShift,
            Keycode::LAlt => AppKeycode::LAlt,
            Keycode::RAlt => AppKeycode::RAlt,
            Keycode::Command => AppKeycode::Command,
            Keycode::LOption => AppKeycode::LOption,
            Keycode::ROption => AppKeycode::ROption,
            Keycode::LMeta => AppKeycode::LMeta,
            Keycode::RMeta => AppKeycode::RMeta,
            Keycode::Enter => AppKeycode::Enter,
            Keycode::Up => AppKeycode::Up,
            Keycode::Down => AppKeycode::Down,
            Keycode::Left => AppKeycode::Left,
            Keycode::Right => AppKeycode::Right,
            Keycode::Backspace => AppKeycode::Backspace,
            Keycode::CapsLock => AppKeycode::CapsLock,
            Keycode::Tab => AppKeycode::Tab,
            Keycode::Home => AppKeycode::Home,
            Keycode::End => AppKeycode::End,
            Keycode::PageUp => AppKeycode::PageUp,
            Keycode::PageDown => AppKeycode::PageDown,
            Keycode::Insert => AppKeycode::Insert,
            Keycode::Delete => AppKeycode::Delete,
            Keycode::Numpad0 => AppKeycode::Numpad0,
            Keycode::Numpad1 => AppKeycode::Numpad1,
            Keycode::Numpad2 => AppKeycode::Numpad2,
            Keycode::Numpad3 => AppKeycode::Numpad3,
            Keycode::Numpad4 => AppKeycode::Numpad4,
            Keycode::Numpad5 => AppKeycode::Numpad5,
            Keycode::Numpad6 => AppKeycode::Numpad6,
            Keycode::Numpad7 => AppKeycode::Numpad7,
            Keycode::Numpad8 => AppKeycode::Numpad8,
            Keycode::Numpad9 => AppKeycode::Numpad9,
            Keycode::NumpadSubtract => AppKeycode::NumpadSubtract,
            Keycode::NumpadAdd => AppKeycode::NumpadAdd,
            Keycode::NumpadDivide => AppKeycode::NumpadDivide,
            Keycode::NumpadMultiply => AppKeycode::NumpadMultiply,
            Keycode::NumpadEquals => AppKeycode::NumpadEquals,
            Keycode::NumpadEnter => AppKeycode::NumpadEnter,
            Keycode::NumpadDecimal => AppKeycode::NumpadDecimal,
            Keycode::Grave => AppKeycode::Grave,
            Keycode::Minus => AppKeycode::Minus,
            Keycode::Equal => AppKeycode::Equal,
            Keycode::LeftBracket => AppKeycode::LeftBracket,
            Keycode::RightBracket => AppKeycode::RightBracket,
            Keycode::BackSlash => AppKeycode::BackSlash,
            Keycode::Semicolon => AppKeycode::Semicolon,
            Keycode::Apostrophe => AppKeycode::Apostrophe,
            Keycode::Comma => AppKeycode::Comma,
            Keycode::Dot => AppKeycode::Dot,
            Keycode::Slash => AppKeycode::Slash,
        }
    }
}

impl Into<Keycode> for AppKeycode {
    fn into(self) -> Keycode {
        match self {
            AppKeycode::Key0 => Keycode::Key0,
            AppKeycode::Key1 => Keycode::Key1,
            AppKeycode::Key2 => Keycode::Key2,
            AppKeycode::Key3 => Keycode::Key3,
            AppKeycode::Key4 => Keycode::Key4,
            AppKeycode::Key5 => Keycode::Key5,
            AppKeycode::Key6 => Keycode::Key6,
            AppKeycode::Key7 => Keycode::Key7,
            AppKeycode::Key8 => Keycode::Key8,
            AppKeycode::Key9 => Keycode::Key9,
            AppKeycode::A => Keycode::A,
            AppKeycode::B => Keycode::B,
            AppKeycode::C => Keycode::C,
            AppKeycode::D => Keycode::D,
            AppKeycode::E => Keycode::E,
            AppKeycode::F => Keycode::F,
            AppKeycode::G => Keycode::G,
            AppKeycode::H => Keycode::H,
            AppKeycode::I => Keycode::I,
            AppKeycode::J => Keycode::J,
            AppKeycode::K => Keycode::K,
            AppKeycode::L => Keycode::L,
            AppKeycode::M => Keycode::M,
            AppKeycode::N => Keycode::N,
            AppKeycode::O => Keycode::O,
            AppKeycode::P => Keycode::P,
            AppKeycode::Q => Keycode::Q,
            AppKeycode::R => Keycode::R,
            AppKeycode::S => Keycode::S,
            AppKeycode::T => Keycode::T,
            AppKeycode::U => Keycode::U,
            AppKeycode::V => Keycode::V,
            AppKeycode::W => Keycode::W,
            AppKeycode::X => Keycode::X,
            AppKeycode::Y => Keycode::Y,
            AppKeycode::Z => Keycode::Z,
            AppKeycode::F1 => Keycode::F1,
            AppKeycode::F2 => Keycode::F2,
            AppKeycode::F3 => Keycode::F3,
            AppKeycode::F4 => Keycode::F4,
            AppKeycode::F5 => Keycode::F5,
            AppKeycode::F6 => Keycode::F6,
            AppKeycode::F7 => Keycode::F7,
            AppKeycode::F8 => Keycode::F8,
            AppKeycode::F9 => Keycode::F9,
            AppKeycode::F10 => Keycode::F10,
            AppKeycode::F11 => Keycode::F11,
            AppKeycode::F12 => Keycode::F12,
            AppKeycode::F13 => Keycode::F13,
            AppKeycode::F14 => Keycode::F14,
            AppKeycode::F15 => Keycode::F15,
            AppKeycode::F16 => Keycode::F16,
            AppKeycode::F17 => Keycode::F17,
            AppKeycode::F18 => Keycode::F18,
            AppKeycode::F19 => Keycode::F19,
            AppKeycode::F20 => Keycode::F20,
            AppKeycode::Escape => Keycode::Escape,
            AppKeycode::Space => Keycode::Space,
            AppKeycode::LControl => Keycode::LControl,
            AppKeycode::RControl => Keycode::RControl,
            AppKeycode::LShift => Keycode::LShift,
            AppKeycode::RShift => Keycode::RShift,
            AppKeycode::LAlt => Keycode::LAlt,
            AppKeycode::RAlt => Keycode::RAlt,
            AppKeycode::Command => Keycode::Command,
            AppKeycode::LOption => Keycode::LOption,
            AppKeycode::ROption => Keycode::ROption,
            AppKeycode::LMeta => Keycode::LMeta,
            AppKeycode::RMeta => Keycode::RMeta,
            AppKeycode::Enter => Keycode::Enter,
            AppKeycode::Up => Keycode::Up,
            AppKeycode::Down => Keycode::Down,
            AppKeycode::Left => Keycode::Left,
            AppKeycode::Right => Keycode::Right,
            AppKeycode::Backspace => Keycode::Backspace,
            AppKeycode::CapsLock => Keycode::CapsLock,
            AppKeycode::Tab => Keycode::Tab,
            AppKeycode::Home => Keycode::Home,
            AppKeycode::End => Keycode::End,
            AppKeycode::PageUp => Keycode::PageUp,
            AppKeycode::PageDown => Keycode::PageDown,
            AppKeycode::Insert => Keycode::Insert,
            AppKeycode::Delete => Keycode::Delete,
            AppKeycode::Numpad0 => Keycode::Numpad0,
            AppKeycode::Numpad1 => Keycode::Numpad1,
            AppKeycode::Numpad2 => Keycode::Numpad2,
            AppKeycode::Numpad3 => Keycode::Numpad3,
            AppKeycode::Numpad4 => Keycode::Numpad4,
            AppKeycode::Numpad5 => Keycode::Numpad5,
            AppKeycode::Numpad6 => Keycode::Numpad6,
            AppKeycode::Numpad7 => Keycode::Numpad7,
            AppKeycode::Numpad8 => Keycode::Numpad8,
            AppKeycode::Numpad9 => Keycode::Numpad9,
            AppKeycode::NumpadSubtract => Keycode::NumpadSubtract,
            AppKeycode::NumpadAdd => Keycode::NumpadAdd,
            AppKeycode::NumpadDivide => Keycode::NumpadDivide,
            AppKeycode::NumpadMultiply => Keycode::NumpadMultiply,
            AppKeycode::NumpadEquals => Keycode::NumpadEquals,
            AppKeycode::NumpadEnter => Keycode::NumpadEnter,
            AppKeycode::NumpadDecimal => Keycode::NumpadDecimal,
            AppKeycode::Grave => Keycode::Grave,
            AppKeycode::Minus => Keycode::Minus,
            AppKeycode::Equal => Keycode::Equal,
            AppKeycode::LeftBracket => Keycode::LeftBracket,
            AppKeycode::RightBracket => Keycode::RightBracket,
            AppKeycode::BackSlash => Keycode::BackSlash,
            AppKeycode::Semicolon => Keycode::Semicolon,
            AppKeycode::Apostrophe => Keycode::Apostrophe,
            AppKeycode::Comma => Keycode::Comma,
            AppKeycode::Dot => Keycode::Dot,
            AppKeycode::Slash => Keycode::Slash,
        }
    }
}
