name: Cargo Build & Test Main Branch

on:
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Chip-8 - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libxdo-dev
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  