name: Cargo Build & Test

on:
  workflow_dispatch:
 #push:
 #   branches:
 #     - dev

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libxdo-dev
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  